export default {
  shared: {
    testPics: [
      './assets/dancers-gaze.jpg',
      './assets/foto8.jpg',
      './assets/foto21.jpg',
      './assets/image1-small-23.png'
    ],
    photosPics: [
      'aprilfestejos.jpg',
      'consuladoA.jpg',
      'couple01s.jpg',
      'couple03s.jpg',
      'couples05s.jpg',
      'fot10b.jpg',
      'fot11b.jpg',
      'fot12b.jpg',
      'fot13b.jpg',
      'fot14b.jpg',
      'fot1b_.jpg',
      'fot2b.jpg',
      'fot3b.jpg',
      'fot4b.jpg',
      'fot5b.jpg',
      'fot6b.jpg',
      'fot7b.jpg',
      'fot8b.jpg',
      'fot9b.jpg',
      'foto1.jpg',
      'foto10.jpg',
      'foto11.jpg',
      'foto12.jpg',
      'foto13.jpg',
      'foto14.jpg',
      'foto15.jpg',
      'foto16.jpg',
      'foto17.jpg',
      'foto18.jpg',
      'foto19.jpg',
      'foto2.jpg',
      'foto20.jpg',
      'foto21.jpg',
      'foto22.jpg',
      'foto23-small.jpg',
      'foto24-small.jpg',
      'foto25.jpg',
      'foto26.jpg',
      'foto27-small.jpg',
      'foto28-small.jpg',
      'foto3.jpg',
      'foto30-small.jpg',
      'foto31-small.jpg',
      'foto4.jpg',
      'foto5b.jpg',
      'foto6.jpg',
      'foto8.jpg',
      'foto9.jpg',
      'fotohome2.jpg',
      'jeanineprimeras.jpg',
      'margotts.jpg',
      'semblanzagaleriasmall.jpg',
    ]
  },
  contactState: {
    dbInfo: false
  }
}
